---
- name: Install MongoDB and dependencies on Rocky 9
  hosts: database
  become: true
  gather_facts: true
  tasks:
    - name: Check if Ansible user has passwordless sudo
      ansible.builtin.command: sudo -n true
      register: sudo_check
      ignore_errors: true
      changed_when: sudo_check.rc != 0

    - name: Configure passwordless sudo for Ansible user
      become: true
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/ansible
        create: true
        state: present
        line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
        validate: '/usr/sbin/visudo -cf %s'
      when: sudo_check.rc != 0

    - name: Verify passwordless sudo configuration
      ansible.builtin.command: sudo -n true
      register: sudo_check_verify
      ignore_errors: true
      failed_when: sudo_check_verify.rc != 0

    - name: Display status of passwordless sudo
      ansible.builtin.debug:
        msg: "Passwordless sudo for user '{{ ansible_user }}' is configured."
      when: sudo_check_verify.rc == 0

    - name: Ensure pip is installed
      ansible.builtin.dnf:
        name: python3-pip
        state: present

    - name: Install pymongo
      ansible.builtin.pip:
        name: pymongo
        state: present
        executable: pip3 # Explicitly use pip3

    - name: Add MongoDB repository
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/mongodb-org-7.repo
        content: |
          [mongodb-org-7.0]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/redhat/9/mongodb-org/7.0/x86_64/
          gpgcheck=1
          enabled=1
          gpgkey=https://www.mongodb.org/static/pgp/server-7.0.asc
        mode: '0644'

    - name: Install MongoDB
      ansible.builtin.dnf:
        name:
          - mongodb-org
        state: present

    - name: Start and enable MongoDB
      ansible.builtin.systemd_service:
        name: mongod
        state: started
        enabled: true

    - name: Configure MongoDB to listen on all interfaces
      ansible.builtin.lineinfile:
        path: /etc/mongod.conf
        regexp: '^  bindIp:'
        line: '  bindIp: 0.0.0.0'
      notify: Restart MongoDB

    - name: Allow incoming TCP traffic on MongoDB port 27017
      ansible.posix.firewalld:
        port: "{{ mongodb_port }}/tcp"
        permanent: true
        state: enabled

    - name: Reload firewalld to apply changes
      ansible.builtin.systemd_service:
        name: firewalld
        state: reloaded

    - name: Create MongoDB admin user
      community.mongodb.mongodb_user:
        database: admin
        name: admin
        password: "{{ lookup('cypher', 'secret=secret/mongodb_admin_password') }}"
        roles: "root"
        state: present

    - name: Create MongoDB application user
      community.mongodb.mongodb_user:
        database: "{{ mongodb_db }}"
        name: "{{ mongodb_user }}"
        password: "{{ mongodb_password }}"
        roles: "readWrite"
        state: present

  handlers:
    - name: Restart MongoDB
      ansible.builtin.systemd_service:
        name: mongod
        state: restarted

...