---
- name: Install MongoDB and dependencies on Rocky 9
  hosts: database
  become: yes
  gather_facts: true
  vars:
    mongodb_password: "{{ lookup('cypher', 'secret=secret/mongodb_password') }}"
    ansible_python_interpreter: /usr/bin/python3.9
  tasks:
    - name: Check if Ansible user has passwordless sudo
      command: sudo -n true
      register: sudo_check
      ignore_errors: yes
      changed_when: sudo_check.rc != 0

    - name: Configure passwordless sudo for Ansible user
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/ansible
        create: yes
        state: present
        line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
        validate: '/usr/sbin/visudo -cf %s'
      when: sudo_check.rc != 0

    - name: Verify passwordless sudo configuration
      command: sudo -n true
      register: sudo_check_verify
      ignore_errors: yes
      failed_when: sudo_check_verify.rc != 0

    - name: Display status of passwordless sudo
      debug:
        msg: "Passwordless sudo for user '{{ ansible_user }}' is configured."
      when: sudo_check_verify.rc == 0

    - name: Ensure pip is installed
      ansible.builtin.dnf:
        name: python3-pip
        state: present

    - name: Install pymongo
      pip:
        name: pymongo
        state: present
        executable: pip3 # Explicitly use pip3

    - name: Add MongoDB repository
      copy:
          dest: /etc/yum.repos.d/mongodb-org-7.repo
          content: |
            [mongodb-org-7.0]
            name=MongoDB Repository
            baseurl=https://repo.mongodb.org/yum/redhat/9/mongodb-org/7.0/x86_64/
            gpgcheck=1
            enabled=1
            gpgkey=https://www.mongodb.org/static/pgp/server-7.0.asc
          mode: '0644'

    - name: Install MongoDB
      dnf:
        name:
          - mongodb-org
        state: present

    - name: Start and enable MongoDB
      service:
        name: mongod
        state: started
        enabled: yes

    - name: Configure MongoDB to listen on all interfaces
      lineinfile:
        path: /etc/mongod.conf
        regexp: '^  bindIp:'
        line: '  bindIp: 0.0.0.0'
      notify: Restart MongoDB

    - name: Create MongoDB admin user
      mongodb_user:
        database: admin
        name: admin
        password: "{{ lookup('cypher', 'secret=secret/mongodb_admin_password') }}"
        roles: "root"
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Create MongoDB application user
      mongodb_user:
        database: "{{ mongodb_db }}"
        name: "{{ mongodb_user }}"
        password: "{{ mongodb_password }}"
        roles: "readWrite"
        state: present
      when: ansible_facts['os_family'] == "RedHat"

  handlers:
    - name: Restart MongoDB
      service:
        name: mongod
        state: restarted