---
- name: Install Node.js and dependencies on Rocky 9
  hosts: application
  become: yes
  vars:
    mongodb_host: "{{ hostvars['mongodb_vm']['ansible_host'] }}"
    mongodb_password: "{{ lookup('cypher', 'secret=secret/mongodb_password') }}"
    ansible_python_interpreter: /usr/bin/python3.9
    node_version: "20" # Or your desired Node.js version

  tasks:
    - name: Remove conflicting nsolid packages
      dnf:
        name:
          - nsolid-20.10.0-ns5.0.1.x86_64
          - nsolid-20.10.0-ns5.0.2.x86_64
          - nsolid-20.11.0-ns5.0.3.x86_64
        state: absent
      ignore_errors: yes

    - name: Install EPEL repository for additional packages
      dnf:
        name: epel-release
        state: present

    - name: Add Node.js repository
      shell: |
        curl -fsSL https://rpm.nodesource.com/setup_{{ node_version }}.x | bash -
      args:
        creates: /etc/yum.repos.d/nodesource-el9.repo

    - name: Install Node.js (without npm initially)
      dnf:
        name: nodejs
        state: present

    - name: Install correct npm from nodesource (explicitly)
      dnf:
        name: npm
        enablerepo: nodesource-nodejs
        state: present
        # Try these options if the above fails:
        # disable_gpg_check: yes
        # nobest: yes

    - name: Verify npm version
      command: npm -v
      register: npm_version
      changed_when: false
      failed_when: npm_version.rc != 0

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create a simple Node.js app
      copy:
        dest: "{{ app_dir }}/index.js"
        content: |
          const MongoClient = require('mongodb').MongoClient;
          const url = 'mongodb://{{ mongodb_user }}:{{ mongodb_password }}@{{ mongodb_host }}:27017';
          const dbName = '{{ mongodb_db }}';

          MongoClient.connect(url, function(err, client) {
            if (err) throw err;
            console.log("Connected to MongoDB!");
            const db = client.db(dbName);
            db.collection('test').insertOne({ message: "Hello World" }, function(err, res) {
              if (err) throw err;
              console.log("Inserted document!");
              client.close();
            });
          });

          const http = require('http');
          const hostname = '0.0.0.0';
          const port = 3000;
          const server = http.createServer((req, res) => {
            res.statusCode = 200;
            res.setHeader('Content-Type', 'text/plain');
            res.end('Hello World from Node.js!\n');
          });
          server.listen(port, hostname, () => {
            console.log(`Server running at http://${hostname}:${port}/`);
          });
        mode: '0644'

    - name: Install MongoDB Node.js driver
      npm:
        name: mongodb
        path: "{{ app_dir }}"
        state: present

    - name: Start Node.js app with nohup
      command: "nohup node {{ app_dir }}/index.js &"
      args:
        chdir: "{{ app_dir }}"
      async: 10
      poll: 0