---
- name: Install Node.js and dependencies on Rocky 9
  hosts: application
  become: yes
  vars:
    mongodb_host: "{{ hostvars['mongodbww.localdomain']['ansible_host'] }}"
    mongodb_password: "{{ lookup('cypher', 'secret=secret/mongodb_password') }}"
    node_version: "20" # Ensure this matches the installed version
    ansible_python_interpreter: /usr/bin/python3.9
    app_dir: /opt/nodejs_app # Define app_dir here if not already defined

  tasks:
    - name: Remove conflicting nsolid packages
      dnf:
        name:
          - nsolid-20.10.0-ns5.0.1.x86_64
          - nsolid-20.10.0-ns5.0.2.x86_64
          - nsolid-20.11.0-ns5.0.3.x86_64
        state: absent
      ignore_errors: yes

    - name: Install EPEL repository for additional packages
      dnf:
        name: epel-release
        state: present

    - name: Add Node.js repository
      shell: |
        curl -fsSL https://rpm.nodesource.com/setup_{{ node_version }}.x | bash -
      args:
        creates: /etc/yum.repos.d/nodesource-el9.repo

    - name: Install Node.js (including npm from NodeSource)
      dnf:
        name: "nodejs" # Installing 'nodejs' from NodeSource should include the correct npm
        state: present
        enablerepo: nodesource-nodejs
        # Remove the separate npm installation task for now

    - name: Verify npm version
      command: npm -v
      register: npm_version
      changed_when: false
      failed_when: npm_version.rc != 0

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create a simple Node.js app with MongoDB connection
      copy:
        dest: "{{ app_dir }}/index.js"
        content: |
          const { MongoClient } = require('mongodb');
          const http = require('http');

          const mongodbUrl = 'mongodb://{{ mongodb_user | default('admin') }}:{{ mongodb_password }}@{{ mongodb_host }}:27017';
          const dbName = '{{ mongodb_db | default('test') }}';
          const hostname = '0.0.0.0';
          const port = 3000;

          async function startServer() {
            let client;
            try {
              client = await MongoClient.connect(mongodbUrl, { useNewUrlParser: true, useUnifiedTopology: true });
              console.log('Connected to MongoDB!');
              const db = client.db(dbName);

              await db.collection('test').insertOne({ message: 'Hello from Node.js', timestamp: new Date() });
              console.log('Inserted document into MongoDB!');

              const server = http.createServer((req, res) => {
                res.statusCode = 200;
                res.setHeader('Content-Type', 'text/plain');
                res.end('Hello World from Node.js with MongoDB!\n');
              });

              server.listen(port, hostname, () => {
                console.log(`Server running at http://${hostname}:${port}/`);
              });

            } catch (err) {
              console.error('Error:', err);
              process.exit(1);
            }
          }

          startServer();
        mode: '0644'
  
    - name: Create systemd service for Node.js app
      copy:
        dest: /etc/systemd/system/nodejs-app.service
        content: |
          [Unit]
          Description=Node.js Application
          After=network.target

          [Service]
          ExecStart=/usr/bin/node /opt/nodejs_app/index.js
          WorkingDirectory=/opt/nodejs_app
          Restart=always
          User=root
          Group=root
          StandardOutput=journal
          StandardError=journal
          RestartSec=5

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable and start Node.js service
      systemd:
        name: nodejs-app
        enabled: yes
        state: restarted

    - name: Wait for Node.js app to be available
      wait_for:
        host: 0.0.0.0
        port: 3000
        state: started
        timeout: 30