---
- name: Install Node.js and dependencies on Rocky 9
  hosts: application
  become: yes
  vars:
    mongodb_host: "{{ hostvars['mongodb_vm']['ansible_host'] }}"
    mongodb_password: "{{ lookup('cypher', 'secret=secret/mongodb_password') }}"
    node_version: "20" # Ensure this matches the installed version
    ansible_python_interpreter: /usr/bin/python3.9

  tasks:
    - name: Remove conflicting nsolid packages
      dnf:
        name:
          - nsolid-20.10.0-ns5.0.1.x86_64
          - nsolid-20.10.0-ns5.0.2.x86_64
          - nsolid-20.11.0-ns5.0.3.x86_64
        state: absent
      ignore_errors: yes

    - name: Install EPEL repository for additional packages
      dnf:
        name: epel-release
        state: present

    - name: Add Node.js repository
      shell: |
        curl -fsSL https://rpm.nodesource.com/setup_{{ node_version }}.x | bash -
      args:
        creates: /etc/yum.repos.d/nodesource-el9.repo

    - name: Install Node.js (including npm from NodeSource)
      dnf:
        name: "nodejs" # Installing 'nodejs' from NodeSource should include the correct npm
        state: present
        enablerepo: nodesource-nodejs
        # Remove the separate npm installation task for now

    - name: Verify npm version
      command: npm -v
      register: npm_version
      changed_when: false
      failed_when: npm_version.rc != 0

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create a simple Node.js app
      copy:
        dest: "{{ app_dir }}/index.js"
        content: |
          # ... (your Node.js app content) ...
        mode: '0644'

    - name: Install MongoDB Node.js driver
      npm:
        name: mongodb
        path: "{{ app_dir }}"
        state: present

    - name: Start Node.js app with nohup
      command: "nohup node {{ app_dir }}/index.js &"
      args:
        chdir: "{{ app_dir }}"
      async: 10
      poll: 0