# playbook_wordpress.yml (Morpheus Integration)
#
# In Morpheus, create 3 cyber secrets
#   Secret/db_user_password
#   secret/db_root_password
#   Secret/db_server_ip
# When you create the catalog item, add a password input for each of these
# and then use the secrets as defaults. Users can create their own secrets
# if they wish and then enter them at the command line.
---
- hosts: web_server
  become: true
  tasks:
    - name: Install required packages
      dnf:
        name:
          - httpd
          - php
          - php-mysqlnd
          - php-fpm
          - wget
          - unzip
          - firewalld
          - mod_ssl
        state: present

    - name: Ensure firewalld is running and enabled
      service:
        name: firewalld
        state: started
        enabled: true

    - name: Allow HTTP and HTTPS through firewall
      firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
      loop:
        - http
        - https
      notify:
        - Reload firewalld

    - name: Start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: true

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.zip
        dest: /tmp/wordpress.zip

    - name: Unzip WordPress
      unarchive:
        src: /tmp/wordpress.zip
        dest: /var/www/html/wordpress/
        remote_src: yes

    - name: Copy WordPress configuration
      copy:
        src: /var/www/html/wordpress/wp-config-sample.php
        dest: /var/www/html/wordpress/wp-config.php
        remote_src: yes

    - name: Configure WordPress database connection
      replace:
        path: /var/www/html/wordpress/wp-config.php
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      loop:
        - { regexp: "database_name_here", replace: "wordpressdb" }
        - { regexp: "username_here", replace: "wordpressuser" }
        - { regexp: "password_here", replace: "{{ db_user_password }}" } # Morpheus variable
        - { regexp: "localhost", replace: "{{ db_server_ip }}" } # Morpheus Variable

    - name: Set ownership and permissions
      file:
        path: /var/www/html/wordpress/
        state: directory
        recurse: yes
        owner: apache
        group: apache

    - name: Restart httpd
      service:
        name: httpd
        state: restarted

  handlers:
    - name: Reload firewalld
      service:
        name: firewalld
        state: reloaded
