- hosts: web_server.localdomain
  become: true
  vars_files:
    - ../vars/main.yml
  vars:
    wordpress_install_dir: "/var/www/html/wordpress"
  tasks:
    - name: Install required packages
      dnf:
        name:
          - httpd
          - php
          - php-mysqlnd
          - php-json
          - wget
        state: present

    - name: Start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: true

    - name: Create WordPress installation directory
      ansible.builtin.file:
        path: "{{ wordpress_install_dir }}"
        state: directory
        mode: '0755'

    - name: Download WordPress
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: /tmp/wordpress.tar.gz
 
    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Copy WordPress config file
      ansible.builtin.template:
        src: "../templates/wp-config-sample.php.j2"  # Relative path from web_server/
        dest: "{{ wordpress_install_dir }}/wp-config.php"
        mode: '0644'
      notify: Restart Apache

#    - name: Copy WordPress configuration
#      copy:
#        src: "{{ item }}"
#        dest: /var/www/html/wordpress/
#        remote_src: yes
#      loop:
#        - wp-config-sample.php
#      notify:
#        - restart httpd
 
#    - name: Configure wp-config.php
#      replace:
#        path: /var/www/html/wordpress/wp-config.php
#        regexp: "{{ item.regexp }}"
#        replace: "{{ item.replace }}"
#      notify:
#        - restart httpd

  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
