- hosts: web_server.localdomain
  become: true
  vars_files:
    - ../vars/main.yml
  tasks:
    - name: Install required packages
      dnf:
        name:
          - httpd
          - php
          - php-mysqlnd
          - php-json
          - wget
        state: present

    - name: Download WordPress
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: /tmp/wordpress.tar.gz
 
    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Copy WordPress configuration
      copy:
        src: "{{ item }}"
        dest: /var/www/html/wordpress/
        remote_src: yes
      loop:
        - wp-config-sample.php
      notify:
        - restart httpd
 
    - name: Configure wp-config.php
      replace:
        path: /var/www/html/wordpress/wp-config.php
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      loop:
        - { regexp: "database_name_here", replace: "{{ wordpress_db_name }}" }
        - { regexp: "username_here", replace: "{{ wordpress_db_user }}" }
        - { regexp: "password_here", replace: "{{ lookup('morpheus_cypher', customOptions.db_User_Password) }}" }
        - { regexp: "localhost", replace: "{{ hostvars[groups['db_server'][0]].ansible_host }}" }
      notify:
        - restart httpd

    - name: Start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: true

  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
