- name: Install MariaDB and dependencies
  hosts: db_server
  become: yes
  vars_files:
    - ../vars/main.yml
  vars:
    mariadb_root_password: "{{ lookup('cypher', 'secret/mysql_root_password') }}"
    wordpress_db_password: "{{ lookup('cypher', 'secret/wp_db_password') }}"
  tasks:
    - name: Debug - Test Cypher password lookups
      ansible.builtin.debug:
        msg: |
          Cypher lookup test:
          - mariadb_root_password is {{ 'set' if mariadb_root_password is defined and mariadb_root_password != '' else 'unset or empty' }}
          - wordpress_db_password is {{ 'set' if wordpress_db_password is defined and wordpress_db_password != '' else 'unset or empty' }}